version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - tea-network

  backend:
    # Assuming your backend has a Dockerfile
    build: ../backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/tea-ecommerce
      - JWT_SECRET=your-jwt-secret-here
    depends_on:
      - mongo
    networks:
      - tea-network

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tea-network

volumes:
  mongo-data:

networks:
  tea-network:
    driver: bridge
