[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-api.com/api"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-staging-backend-api.com/api"
